package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"
	"scylladb/contollers"
	"scylladb/graph/model"
)

// CreateBookListing is the resolver for the createBookListing field.
func (r *mutationResolver) CreateBookListing(ctx context.Context, input model.CreateBookListingInput) (*model.BookListing, error) {
	createdBook, err := contollers.CreateBookListing(ctx, input)
	if err != nil {
		return nil, err
	}
	return createdBook, nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.BookListing, error) {
	readBook, err := contollers.ReadBookListings()
	if err != nil {
		return nil, err
	}
	return readBook, nil
}

// ReadFile is the resolver for the readFile field.
func (r *queryResolver) ReadFile(ctx context.Context, fileURL string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: ReadFile - readFile"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mutationResolver) ReadBucketData(ctx context.Context, fileURL string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: ReadFile - readFile"))
}
