// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BookListing struct {
	ID          string `json:"_id"`
	Title       string `json:"title"`
	Bookname    string `json:"bookname"`
	Description string `json:"description"`
	Author      string `json:"author"`
}

type CreateBookListingInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Bookname    string `json:"bookname"`
	Author      string `json:"author"`
}

type File struct {
	ID       string `json:"id"`
	XAxis    int    `json:"x_axis"`
	YAxis    int    `json:"y_axis"`
	ZoneName string `json:"zone_name"`
	ClubID   string `json:"club_id"`
	FileURL  string `json:"fileUrl"`
}
